# Testrunner Configuration
# This configuration is used by the integration test runner

component:
  binaryPath: ../component/bin/component
  port: 8080
  timeout: 30s

messagebus:
  type: local

testdata:
  scenariosPath: testdata/scenarios
  fixturesPath: testdata/fixtures

validation:
  timeout: 1m0s
  maxRetries: 3
  retryDelay: 1s
